### ISSUE TITLE
Acceptance tests fail

### ISSUE THREAD

**Issue by Tuurlijk** [bitpatroon/typo3_login_service#1]
Both tests receive an empty response from the server

**Comment by bitpatroon** [comment]
Als ik de 2 functionele tests uitvoer, gaan die gewoon goed. 

Ik voer ze uit door 'E2F typo3conf/ext/typo3_login_service/Tests/Functional' op de command prompt uit te voeren.

Weet je zeker dat de fouten niet elders vandaan komen?

![image](https://user-images.githubusercontent.com/17638058/74143038-564cc380-4bfa-11ea-9b22-ba43b46eefb4.png)

**Comment by Tuurlijk** [comment]
Tests falen als ze niet standalone worden uitgevoerd, maar als onderdeel van een suite.
Zou kunnen liggen aan het hardcoden van de host in \CodeLoginControllerTest::loginUserWorksAsExpected()

**Comment by Tuurlijk** [comment]
Ah, excuus. Ik zit verkeerd te kijken. Gaat mis in de acceptance tests
